stages:
  download_dataset:
    cmd: rye run python -m run.download_dataset +dir=local
    deps:
      - run/download_dataset.py
    outs:
      - data/raw
  prepare_train_features:
    cmd: rye run python -m run.prepare_features +dir=local phase=TRAIN
    deps:
      - run/prepare_features.py
      - data/raw
    outs:
      - features/train
  prepare_test_features:
    cmd: rye run python -m run.prepare_features +dir=local phase=TEST
    deps:
      - run/prepare_features.py
      - data/raw
    outs:
      - features/test